var template = require('./content.html');
var eventHelper = require('../../utils/eventHelper');
var newQuestion = require('modules/newQuestion');

// 定义组件
var comm = Vue.extend({
    template: template,
    data: function () {
        return {
            showQuestion:false,
            quesList:[
                {
                    type:'路面',
                    class:'icon-lumianshijian',
                    bgClass:'color-orange',
                    val:[
                        {
                            title:'积水',
                            solution:'专项检测'
                        },{
                            title:'内涝',
                            solution:'专项检测'
                        },{
                            title:'污水溢流',
                            solution:'专项检测'
                        }
                    ]
                },{
                    type:'雨水口',
                    class:'icon-yushuibizi',
                    bgClass:'color-purple',
                    val:[
                        {
                            title:'雨水篦丢失',
                            solution:'维修'
                        },{
                            title:'雨水篦破损',
                            solution:'维修'
                        },{
                            title:'井环破损',
                            solution:'维修'
                        },{
                            title:'井框差',
                            solution:'维修'
                        },{
                            title:'防盗装置破损',
                            solution:'维修'
                        },{
                            title:'违章占压',
                            solution:'执法'
                        },{
                            title:'无证施工',
                            solution:'执法'
                        },{
                            title:'井壁结垢',
                            solution:'清淤'
                        },{
                            title:'井底积泥',
                            solution:'清淤'
                        },{
                            title:'井体机构破损',
                            solution:'维修'
                        }
                    ]
                },{
                    type:'各类检查井',
                    class:'icon-jinggai',
                    bgClass:'color-blue',
                    val:[
                        {
                            title:'井盖丢失',
                            solution:'维修'
                        },{
                            title:'井盖破损',
                            solution:'维修'
                        },{
                            title:'井环破损',
                            solution:'维修'
                        },{
                            title:'井框差',
                            solution:'维修'
                        },{
                            title:'防盗装置破损',
                            solution:'维修'
                        },{
                            title:'违章占压',
                            solution:'执法'
                        },{
                            title:'无证施工',
                            solution:'执法'
                        },{
                            title:'井壁结垢',
                            solution:'清淤'
                        },{
                            title:'井底积泥',
                            solution:'清淤'
                        },{
                            title:'井体机构破损',
                            solution:'维修'
                        }
                    ]
                },{
                    type:'管道、渠箱',
                    class:'icon-qudaoguanli',
                    bgClass:'color-deepPurple',
                    val:[
                        {
                            title:'违章占压',
                            solution:'检测'
                        },{
                            title:'支管暗接',
                            solution:'检测'
                        },{
                            title:'地面塌陷',
                            solution:'检测'
                        },{
                            title:'水位水流(目测数值)',
                            solution:'检测'
                        },{
                            title:'积泥',
                            solution:'清淤'
                        }
                    ]
                },{
                    type:'边沟',
                    class:'icon-qudao',
                    bgClass:'color-yellow',
                    val:[
                        {
                            title:'违章占压',
                            solution:'执法'
                        },{
                            title:'无证施工',
                            solution:'执法'
                        },{
                            title:'边坡稳定',
                            solution:'专项检测'
                        },{
                            title:'渠边种植',
                            solution:'执法'
                        },{
                            title:'水位水流(目测数值)',
                            solution:'清淤'
                        },{
                            title:'淤泥',
                            solution:'清淤'
                        },{
                            title:'盖板缺损',
                            solution:'维修'
                        },{
                            title:'墙体结构',
                            solution:'专项检测'
                        }
                    ]
                },{
                    type:'倒虹管',
                    class:'icon-tongdaoguanli',
                    bgClass:'color-green',
                    val:[
                        {
                            title:'两端水位差',
                            solution:'专项检测'
                        },{
                            title:'水流水位',
                            solution:'专项检测'
                        }
                    ]
                },{
                    type:'排放口',
                    class:'icon-wushuixitong',
                    bgClass:'color-lightBlue',
                    val:[
                        {
                            title:'违章占压',
                            solution:'执法'
                        },{
                            title:'挡土墙破损',
                            solution:'维修'
                        },{
                            title:'淤积情况',
                            solution:'清淤'
                        },{
                            title:'底坡冲刷',
                            solution:'专项检测'
                        }
                    ]
                },{
                    type:'闸门、阀门、拍门',
                    class:'icon-shuizax',
                    bgClass:'color-red',
                    val:[
                        {
                            title:'淤积',
                            solution:'清淤'
                        },{
                            title:'机构腐蚀',
                            solution:'维修'
                        },{
                            title:'缺损',
                            solution:'维修'
                        },{
                            title:'启闭灵活性',
                            solution:'维修'
                        },{
                            title:'密闭性',
                            solution:'维修'
                        }
                    ]
                }
            ]
        }
    },
    methods: {
        returnMain:function(){
            eventHelper.emit('openSub');
            eventHelper.emit('change-menu','upload');
            eventHelper.emit('closeUploadBtn');
        },
        openQuestion:function(val){
            this.showQuestion = true;
            eventHelper.emit('uploadList',val);
        }
    },
    mounted: function () {
        eventHelper.on('closeQuestion',function(){
            this.showQuestion = false;
        }.bind(this));
    },
    components: {
        'new-question':newQuestion
    }
});
module.exports = comm;