define([
    'modules/appContent',
    'modules/appDemoForm',
    'modules/appDemoForm/elementForm',
    'modules/appDemoTable',
    'modules/appDemoChart',
    'modules/appProjectTrack',
    'modules/appHome',
    'modules/appInfo',
    'modules/appOrder',
    'modules/appGrid',
     'modules/arcgisPlugin',
    'modules/appUnknown',
    'modules/appGeneralForm',
    'modules/appFormWizard',
    'modules/appFormUpload',
    'modules/appFormButton',
    'modules/appTables',
    'modules/appAdvancedForm',
    'modules/appGeneralElements',
    'modules/appIcons',
    'modules/appGlyphicons',
    'modules/appTableDynamic',
    'modules/appPricingDesign',
    'modules/appCharts',
    'modules/appMorris',
    'modules/appProjectDetail',
    'modules/appMediaGallery',
    'modules/appWidgets',
    'modules/appEcharts'], function (appContent, appDemoForm, elementForm, appDemoTable, appDemoChart, appProjectTrack, appHome, appInfo, appOrder, appGrid,arcgisPlugin, appUnknown,appGeneralForm,appFormWizard,appFormUpload,appFormButton,appTables,appAdvancedForm,appGeneralElements,appIcons,appGlyphicons,appTableDynamic,appPricingDesign,appCharts,appMorris,appOtherCharts,appProjectDetail,appMediaGallery,appWidgets,appEcharts) {
    return {
        'app-content': appContent,
        'app-demo-form': appDemoForm,
        'element-form': elementForm,
        'app-demo-table': appDemoTable,
        'app-demo-chart': appDemoChart,
        'app-project-track': appProjectTrack,
        'app-home': appHome,
        'app-info': appInfo,
        'app-order': appOrder,
        'app-grid': appGrid,
         'arcgis-plugin': arcgisPlugin,
        'app-unknown': appUnknown,
        'app-general-form':appGeneralForm,
        'app-form-wizard':appFormWizard,
        'app-form-upload':appFormUpload,
        'app-form-button':appFormButton,
        'app-tables':appTables,
        'app-advanced-form':appAdvancedForm,
        'app-general-elements':appGeneralElements,
        'app-icons':appIcons,
        'app-glyphicons':appGlyphicons,
        'app-table-dynamic':appTableDynamic,
        'app-pricing-design':appPricingDesign,
        'app-charts':appCharts,
        'app-morris':appMorris,
        'app-project-detail':appProjectDetail,
        'app-media-gallery':appMediaGallery,
        'app-widgets':appWidgets,
        'app-echarts':appEcharts
    }
});