define([
    'modules/appContent',
    'modules/appDemoForm',
    'modules/appDemoForm/elementForm',
    'modules/appDemoTable',
    'modules/appDemoChart',
    'modules/appProjectTrack',
    'modules/appHome',
    'modules/appInfo',
    'modules/appOrder',
    'modules/appGrid',
    'modules/arcgisPlugin',
    'modules/appUnknown',
    'modules/appGeneralForm',
    'modules/appFormWizard',
    'modules/appFormUpload',
    'modules/appFormButton',
    'modules/appTables',
    'modules/appAdvancedForm',
    'modules/appGeneralElements',
    'modules/appIcons',
    'modules/appGlyphicons',
    'modules/appTableDynamic',
    'modules/appPricingDesign',
    'modules/appCharts',
    'modules/appMorris',
    'modules/appProjectDetail',
    'modules/appMediaGallery',
    'modules/appWidgets',
    'modules/appEcharts',
    'modules/appTruck/truck',
    'modules/appCaseManager/disposeDepartment',
    'modules/appCaseManager/caseManager',
    'modules/appInterfaceTest',
    'modules/appSys/dict',
    'modules/appFacilityManager/facilityType',
    'modules/appFacilityManager/facilityManager',
    'modules/appDemo1/companyDemo',
    'modules/appDemo1/companyDemoExt',
    'modules/appDemo1/treeDemo',
    'modules/appDemo1/treeDemoExt',
    'modules/appAlarmManager/alarmType',
    'modules/appIotDeviceManager/iotDevice',
    'modules/appIotDeviceManager/iotPlatformDevice'
], function (appContent,
             appDemoForm,
             elementForm,
             appDemoTable,
             appDemoChart,
             appProjectTrack,
             appHome,
             appInfo,
             appOrder,
             appGrid,
             arcgisPlugin,
             appUnknown,
             appGeneralForm,
             appFormWizard,
             appFormUpload,
             appFormButton,
             appTables,
             appAdvancedForm,
             appGeneralElements,
             appIcons,
             appGlyphicons,
             appTableDynamic,
             appPricingDesign,
             appCharts,
             appMorris,
             appProjectDetail,
             appMediaGallery,
             appWidgets,
             appEcharts,
             truck,
             disposeDepartment,
             caseManager,
             appInterfaceTest,
             dict,
             facilityType,
             facilityManage,
             companyDemo,
             companyDemoExt,
             treeDemo,
             treeDemoExt,
             alarmType,
             iotDevice,
             iotPlatformDevice) {
    return {
        'app-content': appContent,
        'app-demo-form': appDemoForm,
        'element-form': elementForm,
        'app-demo-table': appDemoTable,
        'app-demo-chart': appDemoChart,
        'app-project-track': appProjectTrack,
        'app-home': appHome,
        'app-info': appInfo,
        'app-order': appOrder,
        'app-grid': appGrid,
        'arcgis-plugin': arcgisPlugin,
        'app-unknown': appUnknown,
        'app-general-form': appGeneralForm,
        'app-form-wizard': appFormWizard,
        'app-form-upload': appFormUpload,
        'app-form-button': appFormButton,
        'app-tables': appTables,
        'app-advanced-form': appAdvancedForm,
        'app-general-elements': appGeneralElements,
        'app-icons': appIcons,
        'app-glyphicons': appGlyphicons,
        'app-table-dynamic': appTableDynamic,
        'app-pricing-design': appPricingDesign,
        'app-charts': appCharts,
        'app-morris': appMorris,
        'app-project-detail': appProjectDetail,
        'app-media-gallery': appMediaGallery,
        'app-widgets': appWidgets,
        'app-echarts': appEcharts,
        'truck': truck,
        'disposeDepartment': disposeDepartment,
        'caseManager': caseManager,
        'appInterfaceTest': appInterfaceTest,
        'dict': dict,
        'facilityType': facilityType,
        'facilityManager': facilityManage,
        'companyDemo': companyDemo,
        'companyDemoExt': companyDemoExt,
        'treeDemo': treeDemo,
        'treeDemoExt': treeDemoExt,
        'alarmType': alarmType,
        'iotDevice': iotDevice,
        'iotPlatformDevice': iotPlatformDevice
    }
});