define(['services/monitorService'],function(monitorService){
			var i = 0.1;
			var j = 100;

	return{
		getMonitorItems:function(cb){
			cb({
				 items: [
                 {
                    monitorID:"ABC123",//监控项ID
                    highAlert:"40",//过高报警
                    highWarning:"30",//过高预警
                    name:"ABC",//监控项名字
                    itemTypeName:"voltage",//监控项类型
                    type:1
                },
                {
                    monitorID:"DEF1244",//监控项ID
                    lowAlert:"10",//过高报警
                   	lowWarning:"30",//过高预警
                    name:"def",//监控项名字
                    itemTypeName:"voltage",//监控项类型
                    type:2
                }
                ,
                {
                    monitorID:"GHI1244",//监控项ID
                    lowAlert:"10",//过高报警
                   	lowWarning:"30",//过高预警
                    name:"def",//监控项名字
                    itemTypeName:"voltage",//监控项类型
                    type:3
                } ,
                {
                    monitorID:"GHI1566244",//监控项ID
                    lowAlert:"10",//过高报警
                   	lowWarning:"30",//过高预警
                    name:"def",//监控项名字
                    itemTypeName:"voltage",//监控项类型
                    type:3
                }
            ]
			}); 
		},
		getMonitorItemCurrentValue:function(items,cb){
		monitorService.getMonitorItemCurrentValue(items,cb,function(error){
            console.log('Error',error)
        });
		},
    getMonitorsByFacility:function(facilityID,cb){
        monitorService.getMonitorsByFacility(facilityID,cb,function(error){
            console.log(error);
        });
    },
        getHistoricalDataByMonitor:function(monitorID,startDate,endDate,cb){
            monitorService.getHistoricalDataByMonitor(monitorID,startDate,endDate,function(result){
                cb(result);
            });
        }
}
});