var template = require('./content.html');
var eventHelper = require('../../utils/eventHelper');

// 定义组件
var comm = Vue.extend({
    template: template,
    data: function () {
        return {
            lists:[
                {
                    title:'用户列表1',
                    userName:'张三',
                    userInfo:[
                        {
                            key:'性别',
                            value:'男',
                            icon:'fa-venus-double',
                            id:''
                        },{
                            key:'出生日期',
                            value:'1991/10/24',
                            icon:'fa-calendar',
                            id:''
                        },{
                            key:'户口所在地',
                            value:'广州',
                            icon:'fa-building',
                            id:''
                        },{
                            key:'特长',
                            value:'羽毛球，篮球',
                            icon:'fa-heart',
                            id:''
                        },{
                            key:'邮箱地址',
                            value:'136256132@qq.com',
                            icon:'fa-envelope',
                            id:''
                        },{
                            key:'联系方式',
                            value:'13800138000',
                            icon:'fa-phone',
                            id:''
                        }
                    ]
                },
                {
                    title:'用户列表2',
                    userName:'李四',
                    userInfo:[
                        {
                            key:'性别',
                            value:'男',
                            icon:'fa-venus-double',
                            id:''
                        },{
                            key:'出生日期',
                            value:'1991/10/24',
                            icon:'fa-calendar',
                            id:''
                        },{
                            key:'户口所在地',
                            value:'广州',
                            icon:'fa-building',
                            id:''
                        },{
                            key:'特长',
                            value:'羽毛球，篮球',
                            icon:'fa-heart',
                            id:''
                        },{
                            key:'邮箱地址',
                            value:'136256132@qq.com',
                            icon:'fa-envelope',
                            id:''
                        },{
                            key:'联系方式',
                            value:'13800138000',
                            icon:'fa-phone',
                            id:''
                        }
                    ]
                },
                {
                    title:'用户列表3',
                    userName:'王五',
                    userInfo:[
                        {
                            key:'性别',
                            value:'男',
                            icon:'fa-venus-double',
                            id:''
                        },{
                            key:'出生日期',
                            value:'1991/10/24',
                            icon:'fa-calendar',
                            id:''
                        },{
                            key:'户口所在地',
                            value:'广州',
                            icon:'fa-building',
                            id:''
                        },{
                            key:'特长',
                            value:'羽毛球，篮球',
                            icon:'fa-heart',
                            id:''
                        },{
                            key:'邮箱地址',
                            value:'136256132@qq.com',
                            icon:'fa-envelope',
                            id:''
                        },{
                            key:'联系方式',
                            value:'13800138000',
                            icon:'fa-phone',
                            id:''
                        }
                    ]
                },
                {
                    title:'用户列表4',
                    userName:'张三',
                    userInfo:[
                        {
                            key:'性别',
                            value:'男',
                            icon:'fa-venus-double',
                            id:''
                        },{
                            key:'出生日期',
                            value:'1991/10/24',
                            icon:'fa-calendar',
                            id:''
                        },{
                            key:'户口所在地',
                            value:'广州',
                            icon:'fa-building',
                            id:''
                        },{
                            key:'特长',
                            value:'羽毛球，篮球',
                            icon:'fa-heart',
                            id:''
                        },{
                            key:'邮箱地址',
                            value:'136256132@qq.com',
                            icon:'fa-envelope',
                            id:''
                        },{
                            key:'联系方式',
                            value:'13800138000',
                            icon:'fa-phone',
                            id:''
                        }
                    ]
                },
                {
                    title:'用户列表5',
                    userName:'张三',
                    userInfo:[
                        {
                            key:'性别',
                            value:'男',
                            icon:'fa-venus-double',
                            id:''
                        },{
                            key:'出生日期',
                            value:'1991/10/24',
                            icon:'fa-calendar',
                            id:''
                        },{
                            key:'户口所在地',
                            value:'广州',
                            icon:'fa-building',
                            id:''
                        },{
                            key:'特长',
                            value:'羽毛球，篮球',
                            icon:'fa-heart',
                            id:''
                        },{
                            key:'邮箱地址',
                            value:'136256132@qq.com',
                            icon:'fa-envelope',
                            id:''
                        },{
                            key:'联系方式',
                            value:'13800138000',
                            icon:'fa-phone',
                            id:''
                        }
                    ]
                },
                {
                    title:'用户列表6',
                    userName:'张三',
                    userInfo:[
                        {
                            key:'性别',
                            value:'男',
                            icon:'fa-venus-double',
                            id:''
                        },{
                            key:'出生日期',
                            value:'1991/10/24',
                            icon:'fa-calendar',
                            id:''
                        },{
                            key:'户口所在地',
                            value:'广州',
                            icon:'fa-building',
                            id:''
                        },{
                            key:'特长',
                            value:'羽毛球，篮球',
                            icon:'fa-heart',
                            id:''
                        },{
                            key:'邮箱地址',
                            value:'136256132@qq.com',
                            icon:'fa-envelope',
                            id:''
                        },{
                            key:'联系方式',
                            value:'13800138000',
                            icon:'fa-phone',
                            id:''
                        }
                    ]
                },
                ]
        }
    },
    methods: {},
    mounted: function () {
    },
    components: {}
});
module.exports = comm;